Draw Lines and SP Bars Closes #817
Legend-of-Dragoon-Modding/Severed-Chains pull request #1193
Opened 2024-03-16 18:18 UTC by Zychronix

Draw lines and SP bars updated to OpenGL.

2024-04-14 15:21 UTC, LordMonoxide requested changes

2024-04-14 15:21 UTC, LordMonoxide commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +              final MV transforms = new MV();
We don't want to instantiate anything in the game loop, make this a property on the object like spBars

2024-04-14 15:21 UTC, LordMonoxide commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +              transforms.scaling(right - left, bottom - top, 31.0f);
Z scale should be 1.0f, you're scaling the Z axis by 31x

2024-04-14 15:21 UTC, LordMonoxide commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +    transforms.scaling(x2 - x1 + 1, y2 - y1 + 1, 31.0f);
Same here re: Z scale, just check to make sure it still looks as you expect it to after fixing

2024-04-14 16:00 UTC, Zychronix commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +              final MV transforms = new MV();
Made spBarTransforms final below spBars variable.

2024-04-14 16:01 UTC, Zychronix commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +              transforms.scaling(right - left, bottom - top, 31.0f);
Changed Z to 1.

2024-04-14 16:01 UTC, Zychronix commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +    transforms.scaling(x2 - x1 + 1, y2 - y1 + 1, 31.0f);
Changed Z to 1.

2024-04-15 01:01 UTC, LordMonoxide requested changes

2024-04-15 01:01 UTC, LordMonoxide commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +              spBarTransforms.transfer.set(GPU.getOffsetX() + left, GPU.getOffsetY() + top, 1.0f);
The Z translation should still be 31.0f, we just don't want to be scaling the Z axis by 31x on top of that

2024-04-15 01:01 UTC, LordMonoxide commented on src/main/java/legend/game/combat/ui/BattleHud.java
> +    transforms.scaling(x2 - x1 + 1, y2 - y1 + 1, 31.0f);
Missed this one

2024-04-15 12:36 UTC, merged